function [fitresult, gof,h] = LangmuirFit(V, I,a,b,c,d,color1,color2)
%CREATEFIT(V,I)
%  Create a fit.
%
%  Data for 'LangmuirFit' fit:
%      X Input : V
%      Y Output: I
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Dec-2019 15:12:13

%% Fit: 'LangmuirFit'.
[xData, yData] = prepareCurveData( V, I );

% Set up fittype and options.
ft = fittype( 'a*exp(b*(x-c))-d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [a b c d];


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% Plot fit with data.
%figure( 'Name', 'Langmuir Fit' );
h = plot(fitresult, xData, yData,'predfunc'); hold on;
h(1).Color = color2;
h(2).Color = color1;
h(3).Color = color1;
h(4).Color = color1;
%legend( h, 'Data', 'Fit', 'Location', 'NorthEast' );
% Label axes
xlabel V
ylabel I
grid on

end
