function [fitresult, gof,output] = paschen(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Dec-2019 00:55:39


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'd + x - log(c+x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.MaxIter = 100;
opts.StartPoint = [0.942700205261103 0.238910324973161];

% Fit model to data.
[fitresult, gof,output] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( );
h = plot(fitresult,xData,yData,'predfun');
legend( h, 'Data', 'Fit', 'Location', 'NorthEast' );
% Label axes
xlabel('ln(P)')
ylabel('ln(V)')
title('Paschen Fit');
grid on


